# Generated by Django 5.0.2 on 2024-03-02 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('subject', '0002_alter_subject_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subjects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
        ),
    ]
