# Generated by Django 5.0.2 on 2024-03-02 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mark', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('task', models.CharField(blank=True, max_length=30)),
                ('completed_tasks', models.IntegerField(blank=True, default=0)),
                ('total_score_in_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
